version: '3.1'
services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kamronbek196769*
      - POSTGRES_DB=onlineshop2
    ports:
      - "5433:5432"
    restart: always

  backend: 
    build: .
    image: kamronbekibrohimov/onlineshop
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "3000-3000"
    env_file:
      - .env



